# Generated by Django 3.2.14 on 2023-01-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0007_auto_20230121_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='힌트 내용')),
                ('image', models.TextField(blank=True, null=True, verbose_name='힌트 이미지')),
                ('sequence', models.IntegerField(null=True, verbose_name='보여주는 순서')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('point', models.IntegerField(default=0, verbose_name='힌트를 보기 위한 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='UserSheetHintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('sheet_hint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hint.sheethint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
