# Generated by Django 3.2.16 on 2023-05-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='User ID')),
                ('product_id', models.BigIntegerField(db_index=True, verbose_name='상품 ID')),
                ('product_type', models.CharField(choices=[('POINT', '포인트'), ('ADDITIONAL_POINT', '포인트')], db_index=True, max_length=20, verbose_name='상품 타입')),
                ('tid', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='결제 고유 번호')),
                ('total_price', models.IntegerField(db_index=True, default=0, verbose_name='총 결제 금액')),
                ('total_product_price', models.IntegerField(db_index=True, default=0, verbose_name='제품 결제 금액')),
                ('total_user_paid_price', models.IntegerField(db_index=True, default=0, verbose_name='사용자 결제 금액')),
                ('total_discount_price', models.IntegerField(db_index=True, default=0, verbose_name='총 할인 금액')),
                ('total_product_discount_price', models.IntegerField(db_index=True, default=0, verbose_name='제품 할인 금액')),
                ('total_refund_price', models.IntegerField(db_index=True, default=0, verbose_name='환불 금액')),
                ('status', models.CharField(choices=[('READY', '주문 준비중'), ('FAIL', '주문 실패'), ('CANCEL', '주문 취소'), ('SUCCESS', '주문 성공'), ('REFUND', '환불')], db_index=True, max_length=20, verbose_name='결제 상태')),
                ('payment', models.CharField(db_index=True, max_length=20, verbose_name='결제 수단')),
                ('user_notification_sent', models.BooleanField(default=False, verbose_name='고객 알림 전송 여부')),
                ('success_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='결제 성공 시간')),
                ('has_refund', models.BooleanField(default=False, verbose_name='환불 여부')),
                ('refund_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='환불 시간')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='User ID')),
                ('product_id', models.BigIntegerField(db_index=True, verbose_name='상품 ID')),
                ('product_type', models.CharField(choices=[('POINT', '포인트'), ('ADDITIONAL_POINT', '포인트')], db_index=True, max_length=20, verbose_name='상품 타입')),
                ('product_price', models.IntegerField(db_index=True, default=0, verbose_name='제품 결제 금액')),
                ('discount_price', models.IntegerField(db_index=True, default=0, verbose_name='총 할인 금액')),
                ('user_paid_price', models.IntegerField(db_index=True, default=0, verbose_name='사용자 결제 금액')),
                ('refund_price', models.IntegerField(db_index=True, default=0, verbose_name='환불 금액')),
                ('item_quantity', models.IntegerField(db_index=True, default=0, verbose_name='제품 수량')),
                ('status', models.CharField(choices=[('READY', '주문 준비중'), ('FAIL', '주문 실패'), ('CANCEL', '주문 취소'), ('SUCCESS', '주문 성공'), ('REFUND', '환불')], db_index=True, max_length=20, verbose_name='결제 상태')),
                ('success_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='결제 성공 시간')),
                ('refund_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='환불 시간')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order', verbose_name='주문')),
            ],
        ),
    ]
