# Generated by Django 3.2.16 on 2023-05-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230522_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGivePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(db_index=True, verbose_name='주문 아이디')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='유저 아이디')),
                ('point', models.BigIntegerField(db_index=True, verbose_name='포인트')),
                ('status', models.CharField(choices=[('READY', '지급 준비중'), ('SUCCESS', '지급 완료'), ('FAIL', '지급 실패'), ('CANCEL', '지급 취소')], db_index=True, max_length=20, verbose_name='포인트 지급 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
