# Generated by Django 3.2.16 on 2023-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointproduct',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='additionalpointproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='additionalpointproduct',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격 정보'),
        ),
    ]
