# Generated by Django 3.2.16 on 2023-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='결제 고유 번호'),
        ),
    ]
