# Generated by Django 3.2.16 on 2023-05-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20230522_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('KAKAOPAY', '카카오페이'), ('KAKAOPAY_CARD', '카카오페이-카드'), ('KAKAOPAY_MONEY', '카카오페이-머니')], db_index=True, max_length=20, verbose_name='결제 수단'),
        ),
    ]
