version: "3.7"
services:
  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    hostname: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./docker/mysql_server/conf.d:/etc/mysql/conf.d
      - ./docker/mysql_server/data:/var/lib/mysql
      - ./docker/mysql_server/log:/var/log/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
