# Generated by Django 3.2.16 on 2022-12-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_userstorysolve_solved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetanswer',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserSheetAnswerSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('solved_sheet_version', models.IntegerField()),
                ('solved_answer_version', models.IntegerField()),
                ('solving_status', models.CharField(choices=[('solving', '진행중'), ('solved', '성공')], default='solving', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('solved_time', models.DateTimeField()),
                ('next_sheet_path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.nextsheetpath')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.sheet')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.story')),
                ('user_story_solve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.userstorysolve')),
            ],
        ),
    ]
