# Generated by Django 3.2.16 on 2022-12-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_usersheetanswersolve_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersheetanswersolve',
            name='solved_answer_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersheetanswersolve',
            name='solved_sheet_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersheetanswersolve',
            name='solved_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersheetanswersolve',
            name='solving_status',
            field=models.CharField(choices=[('solving', '진행중'), ('solved', '성공')], db_index=True, default='solving', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersheetanswersolve',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
