# Generated by Django 3.2.14 on 2023-01-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20221217_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextsheetpath',
            options={'verbose_name': '정답에 의한 다음 Sheet 경로', 'verbose_name_plural': '정답에 의한 다음 Sheet 경로'},
        ),
        migrations.AlterModelOptions(
            name='sheetanswer',
            options={'verbose_name': 'Sheet 정답 데이터', 'verbose_name_plural': 'Sheet 정답 데이터'},
        ),
        migrations.AlterField(
            model_name='nextsheetpath',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.sheetanswer', verbose_name='정답'),
        ),
        migrations.AlterField(
            model_name='nextsheetpath',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.sheet', verbose_name='정답을 맞춘 후, 다음 시트'),
        ),
    ]
