# Generated by Django 3.2.16 on 2023-03-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_storyemailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheetanswersolve',
            name='solved_sheet_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.sheetanswer'),
        ),
    ]
