# Generated by Django 3.2.16 on 2023-03-15 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0009_usersheetanswersolve_solved_sheet_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='좋아요 횟수'),
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='수정일')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.story')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story 좋아요',
                'verbose_name_plural': 'Story 좋아요',
            },
        ),
    ]
