# Generated by Django 3.2.16 on 2023-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20230315_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='level',
            field=models.IntegerField(default=0, help_text='0: 하, 1: 중, 2: 상, 3: 최상', verbose_name='난이도'),
        ),
    ]
