# Generated by Django 3.2.16 on 2023-03-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_popularstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='좋아요 횟수'),
        ),
    ]
