# Generated by Django 3.2.16 on 2023-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_popularstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularstory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='삭제 여부'),
        ),
    ]
