# Generated by Django 3.2.16 on 2023-03-25 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0013_alter_story_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='secret_members',
            field=models.ManyToManyField(related_name='secret_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
