# Generated by Django 3.2.16 on 2023-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_story_secret_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='비밀 여부'),
        ),
    ]
