# Generated by Django 3.2.16 on 2023-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_story_is_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='is_secret',
            field=models.BooleanField(db_index=True, default=False, verbose_name='비밀 여부'),
        ),
    ]
