# Generated by Django 3.2.16 on 2023-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_usersheetanswersolvehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetanswer',
            name='is_always_correct',
            field=models.BooleanField(default=False, help_text='어떤 정답이든 성공합니다.', verbose_name='항상 정답 여부'),
        ),
    ]
